### ISSUE TITLE
Any documentation 

### ISSUE THREAD

**Issue by Rugg-0** [bizzyvinci/BSC-NFT-rarity-tool#1]
Any documentation on how to use and ran this. Cost many feature on front end ant in the source file

**Comment by bizzyvinci** [comment]
Not really. You can run this repo like a normal react app, but it's just the frontend.

For the backend, I first scraped all the NFT tokens including their URI data. This can be done in several ways cause there are APIs that provide such service. However, I scraped mine by reading the smart contract directly. Then I calculated the rarity and save them to DB. I choose MongoDB because the token data are json.

For how to calculate rarity, raritytools wrote nice articles including [this](https://raritytools.medium.com/ranking-rarity-understanding-rarity-calculation-methods-86ceaeb9b98c) and [this](https://raritytools.medium.com/introducing-rarity-tools-9b0138e992b3).

I hope that helps.

**Comment by Rugg-0** [comment]
yeah it all good now

**Comment by Rugg-0** [comment]
Hey Man sorry but find it hard to customized the script with my own nft Tokens

**Comment by bizzyvinci** [comment]
You can contact me by email horlasehinde@gmail.com.

Do you want to edit because you want to add a token? You can share me the contract address to take a look.

I use a backend api which I haven't made public because it looks ugly.

**Comment by Rugg-0** [comment]
just sent you an email
